/*-------------------------------------------------------------------------*/
/**
   @file
   @author  Lars Möllendorf
   @brief   Defined constants for iniParser

   This file was generated by CMake. Do not edit directly.

*/
/*--------------------------------------------------------------------------*/

/**
 * Version incremented when incompatible API changes are made.
 */
#define INIPARSER_VERSION_MAJOR 4
/**
 * Version incremented when functionality is added in a backward compatible
 * manner.
 */
#define INIPARSER_VERSION_MINOR 3
/**
 * Version incremented when bugs are fixed in a backward compatible manner.
 */
#define INIPARSER_VERSION_PATCH 0
